include /etc/nginx/modules-enabled/*.conf;

worker_processes auto;
pid /tmp/nginx/nginx.pid;
error_log stderr notice;

events {
  worker_connections 4096;
}

http {
  access_log off;
  default_type application/octet-stream;
  keepalive_timeout 65;

  client_body_temp_path /tmp/nginx/client;
  proxy_temp_path /tmp/nginx/proxy;
  fastcgi_temp_path /tmp/nginx/fastcgi;
  uwsgi_temp_path /tmp/nginx/uwsgi;
  scgi_temp_path /tmp/nginx/scgi;

  server {
    listen 8080;
    server_name _;

    location = /hello {
      default_type text/plain;
      charset utf-8;
      content_by_lua_block {
        ngx.header["x-hoplite"] = "true"
        ngx.print("Hello from Hoplite\n")
      }
    }
  }
}
