events {}

http {
    hoplite_bootstrap /etc/hoplite/app.hal;

    server {
        listen 8080;

        location = /hello {
            hoplite_content hoplite.app/hello;
        }

        location = /delay {
            hoplite_content hoplite.app/delayed;
        }

        location /inspect {
            hoplite_content hoplite.app/inspect;
        }
    }
}
